//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 20:06:36 2024 by ROOT version 6.32.02)
//      from the StreamerInfo in file outFile.root
//////////////////////////////////////////////////////////


#ifndef BeamLineInfo_h
#define BeamLineInfo_h
class BeamLineInfo;

#include "Rtypes.h"
#include "TObject.h"
#include <TString.h>
#include "Riostream.h"
#include <vector>

class BeamLineInfo : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TString     fDetectorName;    //
   double      fZpos;            //
   double      fXpos;            //
   double      fYpos;            //
   double      fthetaZ;          //
   double      fthetaX;          //
   double      fthetaY;          //
   vector<double> fDetectorParameters;    //

   BeamLineInfo();
   BeamLineInfo(BeamLineInfo && ) = default;
   BeamLineInfo &operator=(const BeamLineInfo & );
   BeamLineInfo(const BeamLineInfo & );
   virtual ~BeamLineInfo();

   ClassDef(BeamLineInfo,3); // Generated by MakeProject.
};
#endif
