//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 20:06:36 2024 by ROOT version 6.32.02)
//      from the StreamerInfo in file outFile.root
//////////////////////////////////////////////////////////


#ifndef CheckPointInfo_h
#define CheckPointInfo_h
class CheckPointInfo;

#include "Rtypes.h"
#include "TObject.h"
#include <TString.h>

class CheckPointInfo : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TString     fCheckPointName;    //
   double      fZPos;              //
   double      fZMax;              //
   TString     fPreStepName;       //
   TString     fPostStepName;      //

   CheckPointInfo();
   CheckPointInfo(CheckPointInfo && ) = default;
   CheckPointInfo &operator=(const CheckPointInfo & );
   CheckPointInfo(const CheckPointInfo & );
   virtual ~CheckPointInfo();

   ClassDef(CheckPointInfo,2); // Generated by MakeProject.
};
#endif
