//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 20:06:36 2024 by ROOT version 6.32.02)
//      from the StreamerInfo in file outFile.root
//////////////////////////////////////////////////////////


#ifndef EventInfo_h
#define EventInfo_h
class EventInfo;

#include "Rtypes.h"
#include "TObject.h"

class EventInfo : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fRunNumber;    //
   int         fBurstNumber;    //
   int         fEventNumber;    //
   int         fEventQualityMask;    //
   int         fTimestamp;           //
   int         fTriggerMask;         //
   unsigned short fTriggerFlags;        //
   float          fTriggerTime;         //
   float          fLambda;              //
   float          fInstantaneousIntensity;    //
   int            fMUV3Primitives;            //
   int            fNewCHODPrimitives;         //
   int            fOtherPrimitives;           //

   EventInfo();
   EventInfo(EventInfo && ) = default;
   EventInfo &operator=(const EventInfo & );
   EventInfo(const EventInfo & );
   virtual ~EventInfo();

   ClassDef(EventInfo,2); // Generated by MakeProject.
};
#endif
