//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 20:06:36 2024 by ROOT version 6.32.02)
//      from the StreamerInfo in file outFile.root
//////////////////////////////////////////////////////////


#ifndef NA62Analysis__Core__AnalyzerIdentifier_h
#define NA62Analysis__Core__AnalyzerIdentifier_h
namespace NA62Analysis {
namespace Core {
class AnalyzerIdentifier;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TObjString.h"

namespace NA62Analysis {
namespace Core {
class AnalyzerIdentifier : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TObjString  fAnalyzerName;    //Name of the analyzer

   AnalyzerIdentifier();
   AnalyzerIdentifier(AnalyzerIdentifier && ) = default;
   AnalyzerIdentifier &operator=(const AnalyzerIdentifier & );
   AnalyzerIdentifier(const AnalyzerIdentifier & );
   virtual ~AnalyzerIdentifier();

   ClassDef(AnalyzerIdentifier,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
