//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 20:06:37 2024 by ROOT version 6.32.02)
//      from the StreamerInfo in file outFile.root
//////////////////////////////////////////////////////////


#ifndef NeParticleCandidate_h
#define NeParticleCandidate_h
class NeParticleCandidate;

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"

class NeParticleCandidate : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      fEnergyLKr;    //NeParticleCandidate Energy
   float       fTime;         //NeParticleCandidate time
   TVector3    fPosition;     //the point at the LKr
   float       fSeedEnergyLKr;    //LKr cluster Seed Energy
   float       fNCellsLKr;        //LKr cluster N Cells
   int         fDDeadCellLKr;     //LKr cluster D Dead Cell

   NeParticleCandidate();
   NeParticleCandidate(NeParticleCandidate && ) = default;
   NeParticleCandidate &operator=(const NeParticleCandidate & );
   NeParticleCandidate(const NeParticleCandidate & );
   virtual ~NeParticleCandidate();

   ClassDef(NeParticleCandidate,2); // Generated by MakeProject.
};
#endif
