//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 20:06:36 2024 by ROOT version 6.32.02)
//      from the StreamerInfo in file outFile.root
//////////////////////////////////////////////////////////


#ifndef RecoInfo_h
#define RecoInfo_h
class RecoInfo;

#include "Rtypes.h"
#include "TObject.h"
#include <TString.h>
#include "Riostream.h"
#include <vector>

class RecoInfo : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TString     fRevision;    //Software revision
   unsigned int fNReadEvents;    //Number of read events in the file
   unsigned int fNProcessedEvents;    //Number of processed events in the file
   unsigned int fNSkippedEvents;      //Number of skipped events in the file
   unsigned int fNCriticalEvents;     //Number of events in the file with critical errors
   unsigned int fNPhysicsTriggerEvents;    //Number of PhysicsTrigger events in the file
   unsigned int fNControlTriggerEvents;    //Number of ControlTrigger in the file
   unsigned int fNPeriodicTriggerEvents;    //Number of PeriodicTrigger in the file
   unsigned int fNSpecialTriggerEvents;     //Number of SpecialTrigger in the file
   double       fKaonRate;                  //Kaon rate [MHz] estimated from Cedar
   double       fKaonRateError;             //Error of the Kaon rate [MHz] estimated from Cedar
   vector<unsigned int> fRunID;                     //Run number
   vector<unsigned int> fBurstID;                   //Burst number
   vector<unsigned int> fBurstTime;                 //Burst time (UNIX)
   double               fChokeONTime;               //

   RecoInfo();
   RecoInfo(RecoInfo && ) = default;
   RecoInfo &operator=(const RecoInfo & );
   RecoInfo(const RecoInfo & );
   virtual ~RecoInfo();

   ClassDef(RecoInfo,3); // Generated by MakeProject.
};
#endif
