//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 20:06:37 2024 by ROOT version 6.32.02)
//      from the StreamerInfo in file outFile.root
//////////////////////////////////////////////////////////


#ifndef UpstreamTrack_h
#define UpstreamTrack_h
class UpstreamTrack;

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"

class UpstreamTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    fMomentum;    //
   float       fTimeGTK1;    //
   float       fTimeGTK2;    //
   float       fTimeGTK3;    //
   TVector3    fPosGTK1;     //
   TVector3    fPosGTK2;     //
   TVector3    fPosGTK3;     //
   float       fGTKChi2x;    //
   float       fTimeGTKTrack;    //
   float       fTimeKTAG;        //
   float       fNKTAGSector;     //
   TVector3    fVertex;          //
   float       fCDA;             //
   TVector3    fVertexBT;        //
   float       fVertexBTChi2;    //
   float       fDiscriminant1;    //
   float       fDiscriminant2;    //
   float       fDiscriminantP;    //
   TVector3    fBTDownstreamMomentum;    //
   int         fUpstreamBackground;      //flag for upstream backgrouns: bit 0 at least 1 hit in GTK station with ToT > 23 ns

   UpstreamTrack();
   UpstreamTrack(UpstreamTrack && ) = default;
   UpstreamTrack &operator=(const UpstreamTrack & );
   UpstreamTrack(const UpstreamTrack & );
   virtual ~UpstreamTrack();

   ClassDef(UpstreamTrack,2); // Generated by MakeProject.
};
#endif
